Name:           perl-DateTime-TimeZone
Version:        _VERSION_
Release:        1%{?dist}
Summary:        Time zone object base class and factory
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/DateTime-TimeZone/
Source0:        http://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-TimeZone-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Class::Load)
BuildRequires:  perl(Class::Singleton) >= 1.03
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Params::Validate) >= 0.72
BuildRequires:  perl(parent)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Output)
BuildRequires:  perl(Test::Requires)
Requires:       perl(Class::Load)
Requires:       perl(Class::Singleton) >= 1.03
Requires:       perl(Params::Validate) >= 0.72
Requires:       perl(parent)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This class is the base class for all time zone objects. A time zone is
represented internally as a set of observances, each of which describes the
offset from GMT for a given time period.

%prep
%setup -q -n DateTime-TimeZone-%{version}

# Remove Win32.pm because we are on Linux
rm -Rf ./lib/DateTime/TimeZone/Local/Win32.pm

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%check
make test

%install
rm -rf $RPM_BUILD_ROOT

make install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT

# Move all to /usr/local for incompatibility with perl-DateTime of RHEL
mkdir -p $RPM_BUILD_ROOT/usr/local/share/
cp -a $RPM_BUILD_ROOT/usr/share/* $RPM_BUILD_ROOT/usr/local/share/
rm -Rf $RPM_BUILD_ROOT/usr/share/

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json perltidyrc README
/usr/local/share/perl5/vendor_perl/*
/usr/local/share/man/man3/*

%changelog
* Fri May 09 2014 K1412 1.65-1
- Specfile autogenerated by cpanspec 1.78
- Little adapted for that work on RHEL.
