Name:           perl-POE-Component-Server-SimpleHTTP
Version:        2.18
Release:        _SUB-VERSION_
Summary:        Perl extension to serve HTTP requests in POE
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/POE-Component-Server-SimpleHTTP/
Source0:        http://www.cpan.org/authors/id/B/BI/BINGOS/POE-Component-Server-SimpleHTTP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.6.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Date)
BuildRequires:  perl(HTTP::Request)
BuildRequires:  perl(HTTP::Response)
BuildRequires:  perl(Moose) >= 0.9
BuildRequires:  perl(MooseX::POE) >= 0.205
BuildRequires:  perl(POE) >= 1.0000
BuildRequires:  perl(POE::Filter::HTTP::Parser) >= 1.06
BuildRequires:  perl(Test::More) >= 0.47
BuildRequires:  perl(Test::POE::Client::TCP) >= 0.1
Requires:       perl(HTTP::Date)
Requires:       perl(HTTP::Request)
Requires:       perl(HTTP::Response)
Requires:       perl(Moose) >= 0.9
Requires:       perl(MooseX::POE) >= 0.205
Requires:       perl(MooseX::AttributeHelpers)
Requires:       perl(POE) >= 1.0000
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module makes serving up HTTP requests a breeze in POE.

%prep
%setup -q -n POE-Component-Server-SimpleHTTP-%{version}

%build
(echo 'N' ; echo 'N') | %{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes Changes.svn LICENSE README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun May 11 2014 Jonathan 2.18-1
- Specfile autogenerated by cpanspec 1.78.
